# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wStrvDF-rn_1GlvYRCZG7NUq_X4J9YtU
"""

import pandas as pd
import streamlit as st

# Judul Aplikasi
st.title('Aplikasi Web untuk Menampilkan Hasil Algoritma Perbaikan')

# Deskripsi Aplikasi
st.write("""
Aplikasi ini menampilkan hasil dari algoritma perbaikan data.
""")

# Baca file CSV yang telah dibersihkan
df_clean = pd.read_csv('Cleaned_Data.csv')

# Tampilkan Data yang Telah Dibersihkan
st.write('Data yang telah dibersihkan:')
st.dataframe(df_clean)